### ISSUE TITLE
Exclude migrations from check_pep8.py

### ISSUE THREAD

**Issue by tkw1536** [OpenJUB/dreamjub#4]
When I run check_pep8.py with existing migrations, it gives me a lot of E501 Line too long errors. Since migrations are auto-generated, we should just exclude the appropriate directory.

**Comment by thunderboltsid** [comment]
@GiORg1 Please take a look at this. The file that needs modification is [check_pep8.py](https://github.com/OpenJUB/dreamjub/blob/master/check_pep8.py) in project root. @tkw1536 Can you point us to where the migrations are stored in the project root?

**Comment by tkw1536** [comment]
They are usually stored under APP_NAME/migrations. In our case we have two apps, so that means they should be in: 

```
dreamjub/migrations
login/migrations
```

AFAIK the login app has no models, so currently the second folder does not exist.

**Comment by thunderboltsid** [comment]
@GiORg1 So, for this one you need to modify to the check_pep8.py file to pass these two migration folders as exclude arguments.

**Comment by ghost** [comment]
Fixed with PR #11
