### ISSUE TITLE
Create Application Authorization View

### ISSUE THREAD

**Issue by kuboschek** [OpenJUB/dreamjub#8]
When a user tries to use an app that uses our login, they'll have to grant permissions the first time they login. While Django OAuth toolkit provides a view and template for that, it is not material.
- [ ] Write a custom allow.html template using Polymer elements
- [ ] Subclass the authorization view as required

**Comment by tkw1536** [comment]
@kuboschek Was this solved by merging on #14? Or is this a separate issue?

**Comment by kuboschek** [comment]
Solved by PR #14
